[
                                'label' => 'Menu AdminLTE',
                                'url' => '#',
                                'ico' => 'angle-down',
                                'textClass'=> ['text-info']
                            ],
                            ['label' => 'Dashboard', 'url' => $directoryAsset.'/index.html', 'ico' => 'dashboard' ],
                            ['label' => 'Widgets', 'url' => $directoryAsset.'/pages/widgets.html', 'ico' => 'th', 'badge' => [ 'text' => 'new', 'color' => 'green', 'ico' => 'check' ] ],
                            [
                                'label' => 'Charts',
                                'url' => $directoryAsset.'/#',
                                'ico' => 'bar-chart-o',
                                'items' => [
                                    ['label' => 'Morris', 'url' => $directoryAsset.'/pages/charts/morris.html'],
                                    ['label' => 'Flot', 'url' => $directoryAsset.'/pages/charts/flot.html'],
                                    ['label' => 'Inline chart', 'url' => $directoryAsset.'/pages/charts/inline.html', 'ico' => 'circle'],
                                ],
                            ],
                            [
                                'label' => 'UI Elements',
                                'url' => $directoryAsset.'/#',
                                'ico' => 'laptop',
                                'items' => [
                                    ['label' => 'General', 'url' => $directoryAsset.'/pages/UI/general.html'],
                                    ['label' => 'Icons', 'url' => $directoryAsset.'/pages/UI/icons.html', 'badge' => '11'],
                                    ['label' => 'Buttons', 'url' => $directoryAsset.'/pages/UI/buttons.html'],
                                    ['label' => 'Sliders', 'url' => $directoryAsset.'/pages/UI/sliders.html', 'badge' => [ 'ico' => 'th' ] ],
                                    ['label' => 'Timeline', 'url' => $directoryAsset.'/pages/UI/timeline.html'],
                                ],
                            ],
                            [
                                'label' => 'Forms',
                                'url' => $directoryAsset.'/#',
                                'ico' => 'edit',
                                'items' => [
                                    ['label' => 'General Elements', 'url' => $directoryAsset.'/pages/forms/general.html'],
                                    ['label' => 'Advanced Elements', 'url' => $directoryAsset.'/pages/forms/advanced.html'],
                                    ['label' => 'Editors', 'url' => $directoryAsset.'/pages/forms/editors.html'],
                                ],
                            ],
                            [
                                'label' => 'Tables',
                                'url' => $directoryAsset.'/#',
                                'ico' => 'table',
                                'items' => [
                                    ['label' => 'Simple tables', 'url' => $directoryAsset.'/pages/tables/simple.html'],
                                    ['label' => 'Data tables', 'url' => $directoryAsset.'/pages/tables/data.html'],
                                ],
                            ],
                            ['label' => 'Calendar', 'url' => $directoryAsset.'/pages/calendar.html', 'ico' => 'calendar', 'badge' => [ 'text' => '3', 'color' => 'red' ] ],
                            ['label' => 'Mailbox', 'url' => $directoryAsset.'/pages/mailbox.html', 'ico' => 'envelope', 'badge' => [ 'text' => '12', 'color' => 'yellow' ] ],
                            [
                                'label' => 'Examples',
                                'url' => $directoryAsset.'/#',
                                'ico' => 'folder',
                                'items' => [
                                    ['label' => 'Invoice', 'url' => $directoryAsset.'/pages/examples/invoice.html'],
                                    ['label' => 'Login', 'url' => $directoryAsset.'/pages/examples/login.html'],
                                    ['label' => 'Register', 'url' => $directoryAsset.'/pages/examples/register.html'],
                                    ['label' => 'Lockscreen', 'url' => $directoryAsset.'/pages/examples/lockscreen.html'],
                                    ['label' => '404 Error', 'url' => $directoryAsset.'/pages/examples/404.html'],
                                    ['label' => '500 Error', 'url' => $directoryAsset.'/pages/examples/500.html'],
                                    ['label' => 'Blank Page', 'url' => $directoryAsset.'/pages/examples/blank.html'],
                                ],
                            ],