<?php
     /**************************************************************************************
     * Bookswapp is a web application which allow students to exchange their textbooks
     * It is developed by students of ITE "C. Colamonico" - Sistemi Informativi Aziendali
     * Acquaviva delle Fonti (BA) - Italy
     *
     * Bookswapp is free software; you can redistribute it and/or modify it under
     * the terms of the GNU Affero General Public License version 3 as published by the
     * Free Software Foundation
     *
     * Bookswapp is distributed in the hope that it will be useful, but WITHOUT
     * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
     * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
     * details.
     *
     * You should have received a copy of the GNU Affero General Public License along 
     * with this program; if not, see http://www.gnu.org/licenses or write to the Free
     * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
     * 02110-1301 USA.
     *
     * You can contact ITE "C. Colamonico" with a mailing address at Via Colamonico, 5 
     * 70021 - Acquaviva delle Fonti (BA) Italy, or at email address bookswapp@itccolamonico.it.
     *
     * The interactive user interfaces in original and modified versions
     * of this program must display Appropriate Legal Notices, as required under
     * Section 5 of the GNU Affero General Public License version 3.
     *
     * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
     * these Appropriate Legal Notices must retain the display of the Bookswapp
     * logo and ITE "C. Colamonico" copyright notice. If the display of the logo is not reasonably
     * feasible for technical reasons, the Appropriate Legal Notices must display the words
     * "Copyright ITE C. Colamonico - http://www.itccolamonico.it - 2014. All rights reserved".
     ****************************************************************************************/
?>
<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '\'s UserProfile' => '',
    'Address School' => '',
    'Address User' => '',
    'Adoptions' => '',
    'Advised' => '',
    'Annexes' => '',
    'Annexes Swap' => '',
    'Are you sure you want to delete this item?' => '',
    'Attended Year' => '',
    'Authors' => '',
    'Birthdate' => '',
    'Book ID' => '',
    'Books' => '',
    'Buyer User ID' => '',
    'City School' => '',
    'City User' => '',
    'Class' => '',
    'Classroom ID' => '',
    'Classrooms' => '',
    'Code School' => '',
    'Condition' => '',
    'Condition ID' => '',
    'Course' => '',
    'Course ID' => '',
    'Courses' => '',
    'Create' => '',
    'Create Adoption' => '',
    'Create Book' => '',
    'Create Classroom' => '',
    'Create Course' => '',
    'Create Print Type' => '',
    'Create Publisher' => '',
    'Create School' => '',
    'Create Subject' => '',
    'Create Swap' => '',
    'Create User' => '',
    'Create User Type' => '',
    'Create UserProfile' => '',
    'Create UserRole' => '',
    'Create UserStatus' => '',
    'Created At' => '',
    'Date Bookmark' => '',
    'Date For Sale' => '',
    'Date Swap' => '',
    'Delete' => '',
    'District School' => '',
    'District User' => '',
    'Email1 School' => '',
    'Email2 School' => '',
    'Fax School' => '',
    'First Name' => '',
    'Gender' => '',
    'Gender ID' => '',
    'Geo Lat User' => '',
    'Geo Lng User' => '',
    'Google Book ID' => '',
    'ID' => '',
    'Isbn' => '',
    'Last Name' => '',
    'Name School' => '',
    'Note Swap' => '',
    'Num Vol Serie' => '',
    'Num Volume' => '',
    'Order School' => '',
    'Page Count' => '',
    'Phone1 School' => '',
    'Phone1 User' => '',
    'Phone2 School' => '',
    'Phone2 User' => '',
    'Please Choose One' => '',
    'Possession' => '',
    'Price' => '',
    'Price Adoption' => '',
    'Price Swap' => '',
    'Print Type' => '',
    'Print Type ID' => '',
    'Print Types' => '',
    'Profile' => '',
    'Profiles' => '',
    'Published Date' => '',
    'Publisher' => '',
    'Publisher ID' => '',
    'Publishers' => '',
    'Reserved' => '',
    'Reset' => '',
    'Role' => '',
    'Role Name' => '',
    'Role Value' => '',
    'Roles' => '',
    'School ID' => '',
    'School Verificated User' => '',
    'Schools' => '',
    'Search' => '',
    'Section Class' => '',
    'Seller User ID' => '',
    'Sold' => '',
    'Status' => '',
    'Status Name' => '',
    'Status Value' => '',
    'Statuses' => '',
    'Subject' => '',
    'Subject ID' => '',
    'Subjects' => '',
    'Subtitle' => '',
    'Swaps' => '',
    'The requested page does not exist.' => '',
    'Thumbnail' => '',
    'Title' => '',
    'To Buy' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Updated At' => '',
    'Url School' => '',
    'User' => '',
    'User ID' => '',
    'User Profiles' => '',
    'User Type' => '',
    'User Type Name' => '',
    'User Type Value' => '',
    'User Types' => '',
    'Users' => '',
    'Year Adoption' => '',
    'Zip School' => '',
    'Zip User' => '',
    'yyyy-mm-dd' => '',
    'Class ID' => '@@@@',
    'Book Id' => '@@@@',
];
